version: "3.7"
services:
  server:
    build: ./server
    command: ["npm", "run", "start"]
    volumes:
      - ./server:/server
      - server_nm:/server/node_modules
    ports:
      - 9000:9000

  client:
    build: ./client
    depends_on:
      - server
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./client:/client
      - client_nm:/client/node_modules
    ports:
      - 8080:8080

  e2e:
    build: ./e2e
    depends_on:
      - client
    working_dir: /e2e
    volumes:
      - ./e2e:/e2e

volumes:
  server_nm:
    driver: local
  client_nm:
    driver: local
