version: "3.7"
services:
  server:
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    command: ["npm", "run", "start"]
    ports:
      - 9000:9000

  client:
    build: ./client
    depends_on:
      - server
    volumes:
      - ./client:/client
      - /client/node_modules
    command: ["npm", "run", "start:dev"]
    ports:
      - 8080:8080

  e2e:
    build: ./e2e
    depends_on:
      - client
    volumes:
      - ./e2e:/e2e
      - /e2e/node_modules
    command: ["npm", "run", "test"]
