version: '3.7'
services:
  web:
    build: ./web
    command: ["npm", "run", "start:dev"]
    volumes:
      - ./web:/web
      - web_nm:/web/node_modules
    ports:
      - 8080:8080

volumes:
  web_nm:
    driver: local
